### ISSUE TITLE
When clicking on specific search result - often can't see it in the resulting page due to time mismatch

### ISSUE THREAD

**Issue by Stvad** [marianoguerra/future-of-coding-weekly#111]
There appears to be some time related issue/mismatch between search results and main display view. For example (when searching for `nyc`):

On the search page I get the following result:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/81347/147524614-3d96100d-57f3-43a2-8bd3-e2766242e636.png">

When I click on the date on the message, to view it in the context - I get empty results (telling me that there were no messages on that day)

<img width="751" alt="image" src="https://user-images.githubusercontent.com/81347/147524679-e2d809cd-c60e-40cb-9248-3e98953db0e4.png">

But if I'm to expand the date range - I can see the message again:

<img width="646" alt="image" src="https://user-images.githubusercontent.com/81347/147524735-b10b96e7-29b0-401f-8fe2-61c3831568dc.png">

My current timezone is EST

**Comment by marianoguerra** [comment]
sorry, I have to close the issue to run some scripts and open it again after it :/

**Comment by marianoguerra** [comment]
now the link will open a search with that message context (7 days before and 7 after)

**Comment by Stvad** [comment]
nice! though I wonder if 14 day is too large of an interval 🤔

**Comment by marianoguerra** [comment]
yes, I thought the same :/

PS: just fixed a timezone bug, that may have (also) been your problem
