### ISSUE TITLE
Future of Coding Newsletter 2020/03 Week 2

### ISSUE THREAD

**Issue by marianoguerra** [marianoguerra/future-of-coding-weekly#12]
This issue collects resources for the newsletter of the year/month/week that should be in the title

If you want to contribute open the issue and paste a resource you think is worth sharing in the newsletter and comment on the issue of the week.

**Use markdown for formatting**, ideally **a contribution should have a title a link and optionally a description.**

Post helpers: https://marianoguerra.github.io/future-of-coding-weekly/helpers.html

Use comment reactions on issue comments to up vote/down vote/whatever each submission the reactions that have a clear sense of positive/negative will be considered to rank the submissions of the week.

**Comment by marianoguerra** [comment]
🎥🌐 [Projection Boxes](https://cseweb.ucsd.edu/~lerner/proj-boxes.html) a novel visualization technique for displaying runtime values of programs. via [Shalabh Chaturvedi](https://mobile.twitter.com/chatur_shalabh)

> The key idea behind projection boxes is to start with a full semantics of the program, and then use projections to pick a subset of the semantics to display. 

> By varying the projection used, projection boxes can encode both previously known visualization techniques, and also new ones. 

> As such, projection boxes provide an expressive and configurable framework for displaying runtime information.

**Comment by marianoguerra** [comment]
📝 [Leveraging the “Display Server” to Improve Debugging](https://arcan-fe.com/2020/02/10/leveraging-the-display-server-to-improve-debugging). Via [Kartik Agaram](http://akkartik.name/about)

**Comment by marianoguerra** [comment]
📝 [CLUI: Building a Graphical Command Line](https://blog.repl.it/clui). Via **Jared Windover** (🧵[Slack Thread](https://futureofcoding.slack.com/archives/C5T9GPWFL/p1583512067095400))

**Comment by marianoguerra** [comment]
🎥 [Computers for Cynics - It All Went Wrong at Xerox PARC - Ted Nelson](https://youtube.com/watch?v=c6SUOeAqOjU). Via [Ivan Reese](https://twitter.com/spiralganglion) (🧵[Slack Thread](https://futureofcoding.slack.com/archives/C5T9GPWFL/p1583565732099000))

**Comment by marianoguerra** [comment]
🐦 [Chris Granger](https://twitter.com/ibdknox) asked ["What do you value most in the developer oriented products you use?"](https://twitter.com/ibdknox/status/1234519481617006592) on Twitter and got some interesting responses.

**Comment by ivanreese** [comment]
📝 The Future of Coding community is (finally!) adopting a Code of Conduct. If you want to help, please review the [final draft](https://github.com/futureofcoding/code-of-conduct) and suggest tweaks or additions [in the Slack thread](https://futureofcoding.slack.com/archives/C5T9GPWFL/p1583385195087100).

**Comment by ivanreese** [comment]
It might be worth pointing out that the slack thread for that Ted Nelson Xerox PARC video is now full of stories from our community members who were there at the time, complementing, clarifying, or contradicting the claims Nelson makes in the video.

**Comment by marianoguerra** [comment]
📝 [An app can be a home-cooked meal](https://www.robinsloan.com/notes/home-cooked-app). Via [Kartik Agaram](http://akkartik.name/about) (🧵[Slack Thread](https://futureofcoding.slack.com/archives/C5T9GPWFL/p1583608988119700))

**Comment by marianoguerra** [comment]
[Will Crichton](willcrichton.net):

> I saw a presentation from the CEO of Roblox the other day. He had a pretty strong long-term vision for the platform as a combination of Steam (game platform + social network), Unity (game engine + dev tools), and Second Life (customizable avatar, connected game worlds). Some interesting notes:

> * 65% of 9-12 y/o in the US play Roblox (as monthly active users). They have a comparable audience size to Minecraft.
> * 40% of players are female. It use to be 95/5 male/female 10 years ago.
> * They paid $100 million last year to creators on the platform.

> I hadn’t realized how staggeringly big the platform is, and influential with children. Just something worth thinking about if you’re trying to build for the next generation!

> (And as someone who learned to code in Garry’s Mod, it’s cool to see people get interested in using virtual worlds to teach programming!)

Read the (🧵[Slack Thread](https://futureofcoding.slack.com/archives/C5T9GPWFL/p1583619242127600)) for an interesting conversation

**Comment by marianoguerra** [comment]
https://tinyletter.com/marianoguerra/letters/future-of-coding-newsletter-2020-03-week-2
