### ISSUE TITLE
search: second paragraph of blockquote overflows the blockquote

### ISSUE THREAD

**Issue by akkartik** [marianoguerra/future-of-coding-weekly#198]
Example: https://history.futureofcoding.org/history/?fromDate=2022-10-06&toDate=2022-10-12&channel=linking-together&filter=#2022-10-09T15:37:22.045Z

Expected result: The paragraph starting "As a result" should be within the blockquote. Compare http://akkartik.name/archives/foc/linking-together/1665329842.045579.html

**Comment by marianoguerra** [comment]
I will fix this at some point, I just have to close it each time I make a newsletter release :D

**Comment by marianoguerra** [comment]
![2023-08-06_12-41](https://github.com/marianoguerra/future-of-coding-weekly/assets/68463/4ce31692-e5d2-4848-8028-966d99ae6aa9)
